### ISSUE TITLE
Get wifi working on the BeagleBone so that we can SSH into it without a cable

### ISSUE THREAD

**Issue by CrustyAuklet** [SaddlebackCSS/AutonomousCar#24]
Since the rover is now battery powered, if we can SSH wirelessly we can maybe start some driving tests... :100:

**Comment by ozyx** [comment]
Where are we at with this? Did you figure this out? :octocat: If so... EXCITING!!

**Comment by garlic-hub** [comment]
School wi-fi isn't too great. We might be better off running a hotspot off a phone or just using a router that doesn't have have an actual internet connection since we can still use it for the LAN capabilities since we don't need internet for SSH. That way we can test wherever we go without being restricted.

**Comment by ozyx** [comment]
good idea

**Comment by CrustyAuklet** [comment]
Also the file to describe the AP to connect to is pretty simple if you go look at the reference I put in the readme, so the complicated school wifi username and PW would probably be no fun to get working. I have it working with my home wifi but it is noticeably laggy compared to cable (of course)

**Comment by garlic-hub** [comment]
I have a router i dont use anymore that would work well. Plus since we control the router we can configure it however we need to work as well as possible with the BBB
